name: Netease Auto Signin

on:
  schedule:
    - cron: "0 23 * * *"     # 每天 23:00 UTC (北京时间 07:00)
  workflow_dispatch:         # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Run Signin
        env:
          NETEASE_EMAIL: ${{ secrets.NETEASE_EMAIL }}
          NETEASE_PASSWORD: ${{ secrets.NETEASE_PASSWORD }}
        run: python signin.py
